language: php
sudo: false

matrix:
  include:
    - php: 5.6
      env: PREFER_LOWEST=--prefer-lowest
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: COLLECT_COVERAGE=true
before_script:
  - travis_retry composer install --no-interaction
  - travis_retry composer update $PREFER_LOWEST
script:
  - vendor/bin/phpunit
after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/coveralls; fi
